development:
  adapter: postgresql
  encoding: utf8
  database: localbounties_dev
  username: james
  host: localhost

test: &defaults
  adapter: postgresql
  encoding: utf8
  database: localbounties_test
  username: james
  host: localhost

# up to heroku to figure out the production
production: &defaults
  adapter: postgresql
  encoding: utf8
  password: itf5Y6oqk0Zyg5MyqAggR4s683
  database: d2b8mnkm7q4qpu
  username: mtxghjxiwxbyez
  host: ec2-23-23-201-251.compute-1.amazonaws.com
  port: 5432