development:
  adapter: postgresql
  encoding: utf8
  database: localbounties_dev
  username: connorwarnock
  host: localhost

test: &defaults
  adapter: postgresql
  encoding: utf8
  database: localbounties_test
  username: connorwarnock
  host: localhost

# up to heroku to figure out the production
production: &defaults
  adapter: postgresql
  encoding: utf8
  database: localbounties_production
  username: connorwarnock
  host: localhost